---
  parser: babel-eslint
  extends:
    - standard
  plugins:
    - react
  rules:
    react/jsx-filename-extension: 0
    react/prefer-stateless-function: 0
    react/jsx-uses-react: 2
    react/jsx-uses-vars: 2
    react/react-in-jsx-scope: 2
  globals:
    fetch: false
    window: false
    document: false